### ISSUE TITLE
Versionierung

### ISSUE THREAD

**Issue by sf-janz** [SebastianLuebke/Starface-Module#1]
Hallo Sebastian!

Die Dateinamen die der Module Creator verwented ist bei Versionierung der Module in Git  problematisch.

Ich würde dir empfehlen die Versionsnummer im Dateinamen (_v000.sfm) zu entfernen und [Git Tags](https://git-scm.com/book/en/v2/Git-Basics-Tagging) und [Github Releases](https://help.github.com/en/articles/creating-releases) für diesen Zweck zu nutzen.

**Comment by SebastianLuebke** [comment]
Ja das wollte Ich auch noch ändern. Wollte die Module gleich ohne Passwortschutz nochmal hochladen
