### ISSUE TITLE
Anrufe gehen durch

### ISSUE THREAD

**Issue by HerroBert** [SebastianLuebke/Starface-Module#4]
Hallo!

Ich habe die Starface 6.6.0.20. 
Bei mir gehen die Anrufe trotzdem durch, die Anlage Mail dazu einen Bericht, dass der Anruf blockiert wurde, was aber nicht stimmt.

**Comment by SebastianLuebke** [comment]
Nutz du eine iQueue? In der aktuellsten Version sollte das eigentlich nicht mehr der Fall sein

**Comment by HerroBert** [comment]
Nein, einfach ein normales Sip-Telefon.

**Comment by SebastianLuebke** [comment]
Also bei mir geht es einwandfrei mit der aktuellen Version? Hast du die mal runtergeladen von vor 2 Tagen?

**Comment by HerroBert** [comment]
Ich habe doch mit der Version 6.6.20 die neuste Version.

**Comment by SebastianLuebke** [comment]
Ich rede von der aktuellen Version des Moduls hier auch github. Lad das Modul nochmal runter und teste es dann

**Comment by HerroBert** [comment]
sieht gut aus, ich musste zwar die Blockregel neuanlegen, aber dann gings.
